alupa_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base_site.urls', namespace='base_site')),
]

base_site/urls.py
from django.urls import path
from . import views

app_name = 'base_site'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('login/', views.login, name= 'login'),
    path('cadastro/', views.resgister, name='register'),
    path('produtos/<slug:slug>', views.detail, name='detail' ),
    path('logout/', views.logout, name='logout'),
    path('pedido/', views.pedido, name='pedido'),

]

base_site/models.py
from django.db import models
from autoslug import AutoSlugField

# Create your models here.
from django.urls import reverse
from django.contrib.auth.models import User


class Products(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from='name')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("base_site:detail", kwargs={"slug": self.slug})

class Pedido(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.ForeignKey(Products,on_delete=models.DO_NOTHING)
    qnt = models.IntegerField()
    product_price = models.IntegerField()
    total_price = models.DecimalField(max_digits=6, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

base_site/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as logout_django
from base_site.models import Products
# Create your views here.

def homepage(request):
    product_list = Products.objects.all()
    return render(request, template_name= 'base_site/index.html',context={'product_list':product_list,})

def resgister(request):
    if request.method == 'GET':
        return render(request, template_name= 'base_site/register.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('senha')

        user = User.objects.filter(username=username).first()
        if user:
            return HttpResponse('já existe usuario com este user name')
        user= User.objects.create_user(username = username, email= email, password=password)
        user.save()
        return HttpResponse('usuario cadastrado com sucesso!')

def login(request):
    next_page = request.POST.get('next', '/produtos')
    if request.method == "GET":
        return render(request, template_name= 'base_site/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('senha')
        user = authenticate(username=username, password=password)
        if user:
            login_django(request, user)
            return redirect('/', kwargs={'user':user})
        else:
            return HttpResponse("email ou senha informados estão incorretos")

def logout(request):
    logout_django(request)
    return redirect('/')

def product(request):
    url = request.path
    return render(request, template_name='base_site/produtos.html', context={'url_site':url})

def detail(request, slug):
    product = Products.objects.get(slug=slug)
    return render(request, template_name='base_site/detalhe.html', context= {'product':product,
                                                                             })

def pedido(request):
    return HttpResponse('Este é seu pedido')

base_site/templates/base_site/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

base_site/templates/base_site/detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

{{ product }}
<br>
<p> Descrição do produto: </p>
{{product.description}}
{{next}}
<br>
<br>
<p> Preço </p>
{{product.price}}
<br>
<br>


<script>
function funcao1()
{
alert("Voce precisa estar logado!");
}
</script>

</body>

    {% if user.is_authenticated %}
        <a href="/pedido"><button>Pedido</a>
        <br>
        <br>
        <a href="/logout"><button>Logout</a>

    {% else %}
        <input type="button" onclick="funcao1()" value="Pedido" />
        <br>
        <br>

        <a href="/login"><button>Login</a>

    {% endif %}



</html>

base_site/templates/base_site/index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compartible" content="IE=edge">
    <title>Alupa</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base_site/style.css' %}" />
  </head>
  <body>


    <nav>

  <ul>
    <li><a href="#home">Home</a></li>
    <li><a href="#empresa">Empresa</a></li>
    <li><a href="#produtos">Produtos</a></li>
    <li><a href="#infog">Informações Gerais</a></li>
  </ul>
</nav>


<section id="Casa">
  <h1>Casa</h1>
</section>

<section id="empresa">
  <h1>Empresa</h1>
</section>

<section id="produtos">
  {%for Prod in product_list %}
    <a href="{{ Prod.get_absolute_url }}">{{Prod}}</a>
  {% endfor %}
</section>


<section id="infog">
  <h1>Informações Gerais</h1>
</section>
  </body>
</html>

base_site/templates/base_site/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Area de Login</title>
</head>
<body>
    <form action="{% url 'base_site:login'%}" method="POST">{% csrf_token %}
            <input type="text" placeholder="Nome de usuário" name="username">
            <br>
            <br>
            <input type="password" placeholder="Senha" name="senha">
            <br>
            <br>
            <input type="submit" value="entrar">
            <br>
            <br>
</body>
</html>

base_site/templates/base_site/pedido.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a href="/produtos">produtos</a>
        <a href="/logout">logout</a>
    {% else %}
        <a href="/produtos">produtos</a>
        <a href="/login">login</a>
        <a href="/cadastro">cadastre-se</a>
    {% endif %}
</body>
</html>

base_site/templates/base_site/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro</title>
</head>
<body>
    <form action="{% url 'base_site:register'%}" method="POST">{% csrf_token %}
        <input type="text" placeholder="Nome de usuário" name="username">
        <br>
        <br>
        <input type="email" placeholder="Email" name="email">
        <br>
        <br>
        <input type="password" placeholder="Senha" name="senha">
        <br>
        <br>
        <input type="submit" value="cadastrar">
        <br>
        <br>


    </form>

</body>
</html>